# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lil_jstor', '0003_coloringbook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringbook',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
